### ISSUE TITLE
merge EX forecast scripts

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ShunLiu-NOAA/regional_workflow#37]
1. EMC parallel grid:
guess tm06:
	lon = 1820 ;
	lat = 1092 ;
	lonp = 1821 ;
	latp = 1093 ;
	lev = 66 ;
	levp = 67 ;
anl tm06:
dimensions:
	lon = 1820 ;
	lat = 1092 ;
	lonp = 1821 ;
	latp = 1093 ;
	lev = 66 ;
	levp = 67 ;
RESTART in forecast step at TM06
dimensions:
	xaxis_1 = 1826 ;
	xaxis_2 = 1827 ;
	yaxis_1 = 1099 ;
	yaxis_2 = 1098 ;
	zaxis_1 = 65 ;

**Comment by ShunLiu-NOAA** [comment]
Ben,

In model_configure:
output_grid:             'lambert_conformal'
cen_lon:                 -97.5   # central longitude
cen_lat:                 38.5    # central latitude
stdlat1:                 38.5
stdlat2:                 38.5
nx:                      1799    # number of points along x-axis.
ny:                      1059    # number of points along y-axis.

In input.nml
   &fv_core_nml
         layout   = 28,28
         io_layout = 1,1
         npx      = 1821
         npy      = 1093

Is there any connection between nx/ny and npx/npy?

Thanks.

Shun

**Comment by JacobCarley-NOAA** [comment]
@ShunLiu-NOAA the larger dimensions for the restart file may be related to the step that

**Comment by ShunLiu-NOAA** [comment]
Hi Shun,

npx/npy are the parameters for the ESG grid, which is the computational grid for the model.  nx/ny correspond to the parameters needed by the output grid, the grid on which the post-processed output is written to.  For our CONUS runs, the output grid is lambert conformal and is contained entirely within the ESG grid.

Thanks,
Ben

**Comment by JacobCarley-NOAA** [comment]
woops - sorry about the close/open! I was writing a comment and then tried to discard it and messed up!

**Comment by BenjaminBlake-NOAA** [comment]
@ShunLiu-NOAA  I just responded to your question in an email but I'll respond here too so others can see.

npx/npy are the parameters for the ESG grid, which is the computational grid for the model.  nx/ny correspond to the parameters needed by the output grid, the grid on which the post-processed output is written to.  For our CONUS runs, the output grid is lambert conformal and is contained entirely within the ESG grid.

**Comment by ShunLiu-NOAA** [comment]
@BenjaminBlake-NOAA 
To run forecast, EMC parallel is using 67 fix files while GSL is using29 fix files. Is it means that the version of EMC fv3 is advanced than GSL's version? or the two versions are already diverse? 

EMC version: dirctory of running forecast
/gpfs/dell5/stmp/Shun.Liu/fv3lamda/tmpnwprd/regional_forecast_tm06_2021080112
GSLEMC version: dirctory of running forecast
/gpfs/dell1/ptmp/Shun.Liu/stmp/tmpnwprd/testdomain_rrfs_conus_3km/2021080106/fcst_fv3lam_spinup

**Comment by BenjaminBlake-NOAA** [comment]
@ShunLiu-NOAA  It looks like the GSL forecast is not using the MERRA2 aerosol data (the aeroclim and optics files).  I also don't see links to the sfc_climo fix files (C3359 files)

**Comment by ShunLiu-NOAA** [comment]
sfc_data.tile7.halo0.nc  GSL v.s. EMC
There are more variables in EMC version
![image](https://user-images.githubusercontent.com/8901479/128552857-323d383e-430a-48e7-a7db-5b1c72a4c8e2.png)

**Comment by ShunLiu-NOAA** [comment]
@BenjaminBlake-NOAA and @EricRogers-NOAA 
When I tried to submit forecast job using the same executable as real-time FV3LAMDA , I got the error message below:

 Please verify that both the operating system and the processor support Intel(R) AVX512DQ, AVX512F, AVX512CD, AVX512BW and AVX512VL instructions.

Does this mean that I need load other modules?

Thanks.

**Comment by BenjaminBlake-NOAA** [comment]
@ShunLiu-NOAA  Which queue are you submitting the job to?  The FV3LAMDA executable runs on phase 3.5 (dev2/devhigh2/devmax2), and it is compiled with AVX-512.  If you are trying to run it on phase 3 (dev/devhigh/devmax), it won't work because AVX-512 isn't available there.

**Comment by ShunLiu-NOAA** [comment]
@BenjaminBlake-NOAA Thanks. I will switch from dev to dev2.

**Comment by ShunLiu-NOAA** [comment]
EMC version C3359_mosaic.nc in fix_lam should be same as GSL version
C3359_mosaic.halo4.nc in fix_lam

**Comment by ShunLiu-NOAA** [comment]
vertical level difference:
EMC: /gpfs/dell6/emc/modeling/noscrub/Shun.Liu/fv3lamda/regional_workflow/parm/global_hyblev.l66.txt
GSL: /gpfs/dell6/emc/modeling/noscrub/Shun.Liu/rrfs/test/testdomain_rrfs_conus_3km/fix_am/L65_20mb.txt

Regional workflow should add a new directory "parm" to host parameter files.

exregional_make_ics.sh is updated to use the same configuration file as EMC real-time parallel and should be merged to the develop branch in the future.

**Comment by ShunLiu-NOAA** [comment]
exregional_make_lbcs.sh is updated to use the same configuration as EMC real-time parallel and should be merged to the develop branch in the future.

**Comment by ShunLiu-NOAA** [comment]
exregional_run_analysis.sh and exregional_run_prepstart.sh  are updated to use the same configuration as EMC real-time parallel.

**Comment by ShunLiu-NOAA** [comment]
@BenjaminBlake-NOAA and @EricRogers-NOAA, I am working on an hourly forecast in the product cycle. So the next forecast will rely on the 1-hour restart file from the previous cycle. I know we can set the restart time interval to 1 hour. However, for a 12 hour forecast, I will get 12 restart files, but I only need the first one, is there any other parameter that I can limit the restart output to the first hour only?

**Comment by BenjaminBlake-NOAA** [comment]
@ShunLiu-NOAA  I know that FDIAG was replaced by OUTPUT_FH, which allows you to specify the exact hours you want for the output.  However, I'm not sure if there is a similar parameter for the restart files.  I only know about restart_interval and output_1st_tstep_rst, which creates a restart file for the first time step.

**Comment by ShunLiu-NOAA** [comment]
@BenjaminBlake-NOAA Thank you. When the restart files are more than one, there is a time prefix (20210818.130000.phy_data.nc), there is no time prefix if there is only one restart file. Is there a parameter to control this?

**Comment by BenjaminBlake-NOAA** [comment]
@ShunLiu-NOAA  I'm not sure.  @EricRogers-NOAA  or @JacobCarley-NOAA do you know if such a parameter exists?

**Comment by ShunLiu-NOAA** [comment]
@BenjaminBlake-NOAA @JacobCarley-NOAA I figured out this. 
If restart_interval:        1, there is no only one restart output. 
If restart_interval:     1,2,3, it is restart output for the first three hours.

**Comment by ShunLiu-NOAA** [comment]
Bug fix in exregional_run_fcst.sh. 
Constants with a leading 0 are interpreted as octal numbers.
Remove the leading zero by parameter expansion

change 
FCST_LEN_HRS_thiscycle=${FCST_LEN_HRS_CYCLES[${hr}]}
to
FCST_LEN_HRS_thiscycle=${FCST_LEN_HRS_CYCLES[${hr#0}]}

**Comment by ShunLiu-NOAA** [comment]
add function in exregional_run_prepstart.sh to check the time prefix of the restart file for spinup and prod cycle.

**Comment by ShunLiu-NOAA** [comment]
add function in exregional_run_fcst.sh to generate EMC style POST product.

**Comment by ShunLiu-NOAA** [comment]
add function in exregional_run_fcst.sh to calculate TM mark so that the final product will use the same name convention as EMC real-time parallel.
