### ISSUE TITLE
prepstart_prod failure at 202202120100

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ShunLiu-NOAA/regional_workflow#64]
Ming,

Task prep_cyc_prod failed at 202202120100. Looks like this is related to SST update.
Any idea about this?

Shun

Job failed:
202202120100           prep_cyc_prod                    85259863                DEAD                   1         1         109.0

exregional_run_prepstart.sh:
#-----------------------------------------------------------------------
if [ ${HH} -eq ${SST_update_hour} ] && [ ${cycle_type} == "prod" ] ; then
   echo "Update SST at ${SST_update_hour}z"
   if [ -r "${SST_ROOT}/latest.SST" ]; then
      cp ${SST_ROOT}/latest.SST .
   elif [ -r "${SST_ROOT}/${YYJJJ00000000}" ]; then
      **cp ${SST_ROOT}/${YYJJJ00000000} latest.SST**
   else
     echo "${SST_ROOT} data does not exist!!"
     echo "ERROR: No SST update at ${time_str}!!!!"
   fi
   if [ -r "latest.SST" ]; then
     cp_vrfy ${FIXgsm}/RTG_SST_landmask.dat                RTG_SST_landmask.dat
     ln_vrfy -sf ./latest.SST                                  SSTRTG
     cp_vrfy ${FIX_GSI}/${PREDEF_GRID_NAME}/fv3_akbk       fv3_akbk

cat << EOF > sst.namelist

**Comment by hu5970** [comment]
Shun,
You need to change SST_ROOT to WCOSS path:
Here is the scripts for RAP operation:

9.252 + cp /gpfs/dell1/nco/ops/com/gfs/prod/sst.20220211/rtgssthr_grb_0.083.grib2 SSTRTG
9.402 + ln -s SSTRTG latest.SST
9.408 + cp /gpfs/hps/nco/ops/nwprod/rap.v5.0.11/exec/rap_process_sst .
9.574 + runline='aprun -n 1 -N 1 ./rap_process_sst'

**Comment by ShunLiu-NOAA** [comment]
I think I need more information about this.
Should this be in the same script as exregional_run_prepstart.sh or a separated step?

**Comment by ShunLiu-NOAA** [comment]
lines are added to exregional_run_prepstart.sh
303    elif [ -r "${SST_ROOT}/sst.$YYYYMMDD/rtgssthr_grb_0.083.grib2" ]; then
304       cp ${SST_ROOT}/sst.$YYYYMMDD/rtgssthr_grb_0.083.grib2 latest.SST

**Comment by ShunLiu-NOAA** [comment]
The fix is tested at 2022021400. It works. Will make a PR to RRFS_dev_p0 in https://github.com/ShunLiu-NOAA/regional_workflow/ and then PR to GSL's RRFS_dev1.

**Comment by ShunLiu-NOAA** [comment]
The fix is merged to GSL-RRFS_dev1.
