### ISSUE TITLE
run_post_f014_2022021315 failed

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ShunLiu-NOAA/regional_workflow#68]
Ming, 

Please take a look at this segmentation fault in POST. 

run_post_f014_2022021315 failed

 CALLING MAPS SLP
forrtl: severe (174): SIGSEGV, segmentation fault occurred
Image              PC                Routine            Line        Source
upp.x              00000000013B045D  Unknown               Unknown  Unknown
libpthread-2.17.s  00002B254CFFC630  Unknown               Unknown  Unknown
upp.x              00000000008DA2D4  mdl2sigma_                658  MDL2SIGMA.f
upp.x              00000000006E6FB4  process_                   93  PROCESS.f
upp.x              0000000000641C91  MAIN__                    799  WRFPOST.f
upp.x              00000000004074DE  Unknown               Unknown  Unknown
libc-2.17.so       00002B254D22B555  __libc_start_main     Unknown  Unknown
upp.x              00000000004073E9  Unknown               Unknown  Unknown

**Comment by hu5970** [comment]
Do you have more information on this crash (full log file)? UPP also has many crashes on JET but we cannot repeat the crashes so far. This one is the same like one of crash on JET.

**Comment by ShunLiu-NOAA** [comment]
Yes. I checked JET as well, but I saw different failures from WCOSS. log
files are in
/gpfs/dell1/ptmp/Shun.Liu/ptmp/com/logs/RRFS_NA_3km/RRFS_NA_3km_dev1.20220213/17.

Let me know if you are available for a short tagup.

Shun

**Comment by ShunLiu-NOAA** [comment]
Ming confirmed there were a few similar POST failures on JET. It is no a issue of WCOSS version. The issue is closed and wait for GSL's update.
