### ISSUE TITLE
update RRFS_dev1 with changes on WCOSS

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ShunLiu-NOAA/regional_workflow#76]
As discussed with Ming, the changes on WCOSS need to be merged back to RRFS-dev1.

1. regional workflow changes:
bug fix in line 94 in /gpfs/dell6/emc/modeling/noscrub/Shun.Liu/rrfs_sfe/ufs-srweather-app/regional_workflow/scripts/exregional_run_analysis.sh to remove "PE_MEMER01"
      
2. ufs-srweather-app changes:
/gpfs/dell6/emc/modeling/noscrub/Shun.Liu/rrfs_sfe/ufs-srweather-app/env
build_wcoss_dell_p3_intel.env
build_wcoss_dell_p3_intel.env_DA

3. regional workflow changes:
/gpfs/dell6/emc/modeling/noscrub/Shun.Liu/rrfs_sfe/ufs-srweather-app/regional_workflow/ush/set_rrfs_config.sh

4. machine depended parameters
a.   LAYOUT_X, LAYOUT_Y (28, 30)
b.   ppn in FV3LAM.xml    (28)
c. NCORES_PER_NODE     (28)
d. 
QUEUE_DEFAULT   (dev)
QUEUE_HPSS        (dev)
QUEUE_FCST         (dev)
QUEUE_WGRIB2    (dev)
QUEUE_ANALYSIS (dev)
QUEUE_GRAPHICS (dev)
RRFS_RESERVE       (put nothing here for WCOSS)

e.
    WRTCMP_write_groups="**2**"  (put 2 here, I found 2x28 I/O on WCOSS can reduce about 200s for 1 hr forecast.
    WRTCMP_write_tasks_per_group=$(( 1*LAYOUT_X ))  (use LAYOUT_X here, not Y)
note: should use LAYOUT_X here. LAYOUT_Y should be PPN (processors per node). When IO-LAYOUT_Y=10 is used, LAYOUT_Y should be times of IO-LAYOUT=10, this is not convenient for WCOSS. It is better to use LAYOUT-X=PPN and LAYOUT_Y=times of IO-LAYOUT_Y
f. 
 IO-LAYOUT_Y=10
LAYOUT_X : 28
LAYOUT_Y : 30
5.  
6.

**Comment by hu5970** [comment]
Do you have values for those parameters. They can set through configure. For CONUS 3km, let's keep IO_LAYOUT_Y=1, which is default.

a. LAYOUT_X, LAYOUT_Y   (28, 30)
b. ppn in FV3LAM.xml      (28)
c. NCORES_PER_NODE      (28)
d.
QUEUE_DEFAULT              (dev)
QUEUE_HPSS                   (dev)
QUEUE_FCST                    (dev)
QUEUE_WGRIB2               (dev)
QUEUE_ANALYSIS            (dev)
QUEUE_GRAPHICS           (dev)
RRFS_RESERVE            (put nothing here)
e.
WRTCMP_write_groups="2"
WRTCMP_write_tasks_per_group=$(( 1*LAYOUT_X )) (use LAYOUT_X, not Y)
note: should use LAYOUT_X here. LAYOUT_Y should be PPN (processors per node). When IO-LAYOUT_Y=10 is used, LAYOUT_Y should be times of IO-LAYOUT=10, this is not convenient for WCOSS. It is better to use LAYOUT-X=PPN and LAYOUT_Y=times of IO-LAYOUT_Y
f.
IO-LAYOUT_Y=1
LAYOUT_X  (28)
LAYOUT_Y  (30)

**Comment by ShunLiu-NOAA** [comment]
See the values of parameters above.

**Comment by ShunLiu-NOAA** [comment]
Changes were merged back to GSL's repositories. /gpfs/dell6/emc/modeling/noscrub/Shun.Liu/rrfs_sfex is setup on WCOSS to test the changes.
