### ISSUE TITLE
use GFS netcdf output to generate IC and LBC

### ISSUE THREAD

**Issue by ShunLiu-NOAA** [ShunLiu-NOAA/regional_workflow#79]
Change
FV3GFS_FILE_FMT_ICS="grib2"
FV3GFS_FILE_FMT_LBCS="grib2"
to
FV3GFS_FILE_FMT_ICS="netcdf"
FV3GFS_FILE_FMT_LBCS="netcdf"

**Comment by ShunLiu-NOAA** [comment]
regional workflow can't generate task dependence properly with netcdf files. Task dependencies are still grib files.

**Comment by hu5970** [comment]
Need to add this option in task dependence.

**Comment by ShunLiu-NOAA** [comment]
In this version, I think the link of using netcdf file is broken. Let's have a short meeting to figure out this.

**Comment by hu5970** [comment]
I am testing the netcdf now. We can have a tag-up.

**Comment by ShunLiu-NOAA** [comment]
This is tested in RRFS_P1x
